<?php

/*
|--------------------------------------------------------------------------
| Calculators — single source of truth
|--------------------------------------------------------------------------
| Drives the /calculators hub cards, each tool's SEO meta, the on-page
| how-to guide, the FAQ block (also emitted as FAQPage JSON-LD), and the
| related-peptide bridge. Each entry maps to a widget partial at
| resources/views/calculators/widgets/{slug}.blade.php.
|
| Keep copy research/educational — these tools support peptide *research*,
| not personalized medical dosing. Every page renders the shared disclaimer.
*/

return [

    // ----------------------------------------------------------------------
    'reconstitution' => [
        'slug'        => 'reconstitution',
        'name'        => 'Reconstitution Calculator',
        'short'       => 'Reconstitution',
        'emoji'       => '💉',
        'tagline'     => 'Calculate BAC water, concentration and exact syringe units for any peptide.',
        'category'    => 'Peptide',
        'accent'      => '#2563EB',
        'seo_title'   => 'Peptide Reconstitution Calculator — BAC Water & Syringe Units',
        'seo_description' => 'Free peptide reconstitution calculator. Enter vial mg, bacteriostatic water mL and your target dose to get concentration and the exact units to draw on an insulin syringe.',
        'intro'       => 'Reconstitution is the step that turns a vial of lyophilized (freeze-dried) peptide into an accurately measurable solution. Get the water-to-peptide ratio right and every dose afterwards is simple and repeatable. This calculator does the math for you: enter how much peptide is in the vial, how much bacteriostatic water you are adding, and your target dose — it returns the concentration and the precise number of units to draw on a U-100 insulin syringe.',
        'how_to'      => [
            ['title' => 'Enter the peptide amount', 'body' => 'Type the total milligrams of peptide printed on the vial label (e.g. 5 mg, 10 mg). This is the dry powder amount before any water is added.'],
            ['title' => 'Set the bacteriostatic water volume', 'body' => 'Enter how many millilitres of bacteriostatic (BAC) water you will add. More water makes small doses easier to measure accurately; 1–3 mL is typical.'],
            ['title' => 'Enter your target dose', 'body' => 'Enter the dose you want per injection in micrograms (mcg) or milligrams (mg). The tool converts everything to a single concentration internally.'],
            ['title' => 'Read your syringe units', 'body' => 'The result shows mcg/mL concentration and exactly how many units to draw on a 100-unit insulin syringe, plus the draw volume in mL.'],
        ],
        'faqs'        => [
            ['q' => 'How do you calculate peptide reconstitution?', 'a' => 'Concentration (mcg/mL) = peptide amount in mg × 1000 ÷ water volume in mL. To find units on a U-100 syringe, divide your dose (mcg) by (concentration ÷ 100). This calculator runs both steps automatically.'],
            ['q' => 'What is bacteriostatic water and why use it?', 'a' => 'Bacteriostatic water is sterile water containing 0.9% benzyl alcohol, which inhibits bacterial growth so a multi-use vial stays usable for weeks. It is the standard diluent for reconstituting peptides in research settings.'],
            ['q' => 'How much water should I add to a peptide vial?', 'a' => 'There is no single correct amount — more water simply dilutes the peptide so each unit on the syringe holds less. Choose a volume that puts your target dose at an easy-to-read number of units (e.g. 10–30 units). The calculator lets you test different volumes instantly.'],
            ['q' => 'What does “units” mean on an insulin syringe?', 'a' => 'A U-100 insulin syringe is marked in 100 units per mL, so 1 unit = 0.01 mL. The calculator converts your dose into units so you can draw it directly without separate volume math.'],
        ],
        'related'     => ['bpc-157', 'tb-500', 'semaglutide', 'ipamorelin'],
    ],

    // ----------------------------------------------------------------------
    'bmi' => [
        'slug'        => 'bmi',
        'name'        => 'BMI Calculator',
        'short'       => 'BMI',
        'emoji'       => '📊',
        'tagline'     => 'Calculate Body Mass Index and see your healthy-weight range.',
        'category'    => 'Body',
        'accent'      => '#0EA5E9',
        'seo_title'   => 'BMI Calculator — Body Mass Index, Category & Healthy Range',
        'seo_description' => 'Free BMI calculator. Enter your height and weight in metric or imperial units to get your Body Mass Index, weight category, and the healthy-weight range for your height.',
        'intro'       => 'Body Mass Index (BMI) is a quick screening number that relates your weight to your height. It is widely used as a baseline metric and as a starting point for tracking changes over a weight-management protocol. Enter your height and weight in either metric or imperial units and this calculator returns your BMI, the standard category it falls into, and the weight range considered healthy for your height.',
        'how_to'      => [
            ['title' => 'Choose your units', 'body' => 'Switch between metric (cm / kg) and imperial (ft-in / lb). The calculator converts internally so the result is identical either way.'],
            ['title' => 'Enter height and weight', 'body' => 'Type your height and current weight. Values update the result instantly as you type.'],
            ['title' => 'Read your BMI and category', 'body' => 'The result shows your BMI to one decimal place and the World Health Organization category: underweight, healthy, overweight, or obese.'],
            ['title' => 'See your healthy range', 'body' => 'The tool also shows the weight range that corresponds to a healthy BMI (18.5–24.9) for your exact height, so you have a concrete target.'],
        ],
        'faqs'        => [
            ['q' => 'How is BMI calculated?', 'a' => 'BMI = weight (kg) ÷ height (m)². For imperial units the formula is weight (lb) ÷ height (in)² × 703. This calculator applies the correct formula automatically based on the units you choose.'],
            ['q' => 'What is a healthy BMI range?', 'a' => 'The standard categories are: under 18.5 underweight, 18.5–24.9 healthy, 25–29.9 overweight, and 30 or above obese. These are population screening bands, not a diagnosis.'],
            ['q' => 'Is BMI accurate for everyone?', 'a' => 'BMI does not distinguish muscle from fat, so very muscular people can read as “overweight” while having low body fat. It is a useful population screen and progress tracker, not a complete measure of health.'],
            ['q' => 'How does BMI relate to GLP-1 protocols?', 'a' => 'BMI is a common eligibility and progress metric in weight-management research. Tracking BMI alongside a GLP-1 titration shows trend over time — see the GLP-1 calculator for a projected timeline.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    // ----------------------------------------------------------------------
    'glp-1' => [
        'slug'        => 'glp-1',
        'name'        => 'GLP-1 Calculator',
        'short'       => 'GLP-1',
        'emoji'       => '🔬',
        'tagline'     => 'Model a GLP-1 titration schedule and projected weight-loss timeline.',
        'category'    => 'Peptide',
        'accent'      => '#7C3AED',
        'seo_title'   => 'GLP-1 Calculator — Titration Schedule & Weight-Loss Timeline',
        'seo_description' => 'Free GLP-1 calculator for semaglutide and tirzepatide research. Model a standard titration schedule and an educational projected weight-loss timeline with BMI tracking.',
        'intro'       => 'GLP-1 receptor agonists such as semaglutide and tirzepatide are typically introduced with a gradual “titration” — starting low and stepping the dose up over several weeks to improve tolerability. This educational calculator lays out a standard titration ladder for the compound you select and projects an illustrative weight-loss trajectory based on average percentages reported in the clinical literature, with your BMI tracked at each milestone. It is a planning and learning aid, not medical advice.',
        'how_to'      => [
            ['title' => 'Select the compound', 'body' => 'Choose semaglutide or tirzepatide. Each has its own standard titration ladder and typical maintenance dose range.'],
            ['title' => 'Enter your starting stats', 'body' => 'Provide your height and current weight so the tool can compute starting BMI and translate percentage changes into actual weight.'],
            ['title' => 'Review the titration schedule', 'body' => 'The calculator shows the week-by-week dose steps from the starting dose up to the maintenance range.'],
            ['title' => 'See the projected timeline', 'body' => 'An illustrative trajectory shows estimated weight and BMI at 4, 12, 24, 52 and 68 weeks using average published response rates. Individual results vary widely.'],
        ],
        'faqs'        => [
            ['q' => 'How does GLP-1 titration work?', 'a' => 'Titration means starting at a low dose and increasing it on a fixed schedule (usually every 4 weeks) until reaching a maintenance dose. Stepping up gradually reduces gastrointestinal side effects. The exact ladder depends on the specific compound.'],
            ['q' => 'How much weight is lost on semaglutide vs tirzepatide?', 'a' => 'In published trials, average weight reduction at around 68 weeks was roughly 15% of body weight for semaglutide (STEP) and roughly 20%+ for tirzepatide (SURMOUNT) at higher doses. These are study averages; individual outcomes differ.'],
            ['q' => 'Is this calculator medical advice?', 'a' => 'No. It is an educational model that illustrates standard schedules and average literature outcomes. It does not account for your medical history and is not a substitute for a qualified healthcare professional.'],
            ['q' => 'How do I reconstitute GLP-1 peptides?', 'a' => 'Lyophilized GLP-1 research peptides are reconstituted with bacteriostatic water like any other peptide — use the reconstitution calculator to convert your vial size and dose into syringe units.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide', 'cagrilintide'],
    ],

    // ----------------------------------------------------------------------
    'trt' => [
        'slug'        => 'trt',
        'name'        => 'TRT Calculator',
        'short'       => 'TRT',
        'emoji'       => '💪',
        'tagline'     => 'Convert a weekly testosterone target into per-injection volume and cadence.',
        'category'    => 'Hormone',
        'accent'      => '#DC2626',
        'seo_title'   => 'TRT Calculator — Testosterone Dose, Volume & Injection Frequency',
        'seo_description' => 'Educational TRT calculator. Convert a weekly testosterone target and ester concentration into per-injection volume and a once/twice/EOD frequency split. Research and information only.',
        'intro'       => 'Testosterone replacement is usually prescribed as a weekly milligram target delivered by an oil-based ester (for example testosterone cypionate or enanthate at 200 mg/mL). This calculator converts a weekly target and your vial concentration into the volume per injection and shows how that splits across common cadences (once weekly, twice weekly, or every other day). Testosterone is a controlled substance; this tool is strictly informational and is not medical advice or a recommendation to use it.',
        'how_to'      => [
            ['title' => 'Enter the weekly target', 'body' => 'Type the total weekly testosterone target in milligrams. Common clinical ranges are shown for reference only.'],
            ['title' => 'Set the ester concentration', 'body' => 'Enter the concentration of your preparation in mg/mL (200 mg/mL is the most common for cypionate/enanthate).'],
            ['title' => 'Choose an injection frequency', 'body' => 'Pick once weekly, twice weekly, or every other day. More frequent injections mean a smaller, steadier volume each time.'],
            ['title' => 'Read volume and units', 'body' => 'The result shows the volume per injection in mL and the equivalent units on a U-100 syringe for each cadence.'],
        ],
        'faqs'        => [
            ['q' => 'How do you calculate a testosterone injection volume?', 'a' => 'Volume per week (mL) = weekly dose (mg) ÷ concentration (mg/mL). Divide that by the number of injections per week to get the per-injection volume, then multiply by 100 for U-100 syringe units.'],
            ['q' => 'How often should testosterone be injected?', 'a' => 'Long esters like cypionate and enanthate are commonly split into once- or twice-weekly injections; some protocols use every-other-day for steadier levels. Frequency is a clinical decision made with a prescriber.'],
            ['q' => 'Is this TRT calculator medical advice?', 'a' => 'No. Testosterone is a Schedule III controlled substance. This calculator is an arithmetic aid for educational purposes only and must not be used to self-medicate. Hormone therapy requires a licensed physician and bloodwork.'],
            ['q' => 'What does mg/mL mean on a testosterone vial?', 'a' => 'It is the concentration — how many milligrams of testosterone are dissolved in each millilitre of oil. 200 mg/mL means 1 mL contains 200 mg.'],
        ],
        'related'     => ['tesamorelin', 'ipamorelin', 'cjc-1295-dac'],
    ],

    // ----------------------------------------------------------------------
    'melanotan' => [
        'slug'        => 'melanotan',
        'name'        => 'Melanotan Calculator',
        'short'       => 'Melanotan',
        'emoji'       => '☀️',
        'tagline'     => 'Reconstitute MT-II and map a loading and maintenance schedule.',
        'category'    => 'Peptide',
        'accent'      => '#EA580C',
        'seo_title'   => 'Melanotan II (MT-II) Calculator — Reconstitution & Dosing Schedule',
        'seo_description' => 'Educational Melanotan II calculator. Reconstitute MT-II, convert micro-doses into syringe units, and map a typical loading-then-maintenance schedule. Research information only.',
        'intro'       => 'Melanotan II (MT-II) is a melanocortin peptide studied for its effect on melanogenesis (skin pigmentation). It is supplied as a lyophilized powder and reconstituted with bacteriostatic water like other peptides, but it is typically used at very small micro-doses, which makes accurate syringe-unit conversion important. This calculator reconstitutes your vial, converts a micro-dose into units, and illustrates a common loading-then-maintenance pattern. Educational use only.',
        'how_to'      => [
            ['title' => 'Reconstitute the vial', 'body' => 'Enter the MT-II amount in the vial (commonly 10 mg) and the bacteriostatic water volume you are adding.'],
            ['title' => 'Set your micro-dose', 'body' => 'Enter the dose in micrograms. MT-II is used in small mcg amounts, so the unit conversion is what keeps it accurate.'],
            ['title' => 'Read the units to draw', 'body' => 'The result shows the concentration and the exact units on a U-100 syringe for your micro-dose.'],
            ['title' => 'Review the schedule pattern', 'body' => 'An illustrative loading phase (building up) followed by a maintenance phase (occasional top-ups) is shown for reference.'],
        ],
        'faqs'        => [
            ['q' => 'How do you reconstitute Melanotan II?', 'a' => 'Add bacteriostatic water to the lyophilized MT-II vial and let it dissolve gently. Concentration (mcg/mL) = mg in vial × 1000 ÷ water mL. This calculator converts that into syringe units for your micro-dose.'],
            ['q' => 'Why is MT-II dosed in such small amounts?', 'a' => 'MT-II is potent at the micro-dose level, so doses are measured in micrograms. Adding a known water volume and converting to units prevents over-drawing.'],
            ['q' => 'What is a loading vs maintenance phase?', 'a' => 'A loading phase uses smaller, more frequent doses to build an effect gradually; a maintenance phase uses occasional doses to sustain it. The pattern shown here is illustrative only.'],
            ['q' => 'Is Melanotan II approved for use?', 'a' => 'Melanotan II is not an approved medicine in most jurisdictions and is sold for research only. This calculator is educational and is not a recommendation to use it.'],
        ],
        'related'     => ['melanotan-ii', 'pt-141'],
    ],

    // ----------------------------------------------------------------------
    'fitness' => [
        'slug'        => 'fitness',
        'name'        => 'Fitness Calculator',
        'short'       => 'Fitness',
        'emoji'       => '🏃',
        'tagline'     => 'Calculate BMR, TDEE, calorie targets and a macro split.',
        'category'    => 'Body',
        'accent'      => '#059669',
        'seo_title'   => 'Fitness Calculator — BMR, TDEE, Calories & Macros',
        'seo_description' => 'Free fitness calculator. Get your BMR (Mifflin–St Jeor), TDEE by activity level, calorie targets for cut/maintain/bulk, and a protein-carb-fat macro split.',
        'intro'       => 'Your Basal Metabolic Rate (BMR) is the energy your body uses at rest; your Total Daily Energy Expenditure (TDEE) is BMR scaled by how active you are. Together they set the calorie baseline for any body-composition goal. This calculator uses the Mifflin–St Jeor equation — the modern standard — to estimate BMR and TDEE, then suggests calorie targets for cutting, maintaining or bulking and a sensible macronutrient split.',
        'how_to'      => [
            ['title' => 'Enter your stats', 'body' => 'Provide age, sex, height and weight in metric or imperial units.'],
            ['title' => 'Pick your activity level', 'body' => 'Choose from sedentary up to extremely active. This multiplier turns BMR into TDEE.'],
            ['title' => 'Choose a goal', 'body' => 'Select cut, maintain or bulk. The tool applies a standard calorie deficit or surplus to your TDEE.'],
            ['title' => 'Read calories and macros', 'body' => 'See your BMR, TDEE, daily calorie target and a protein/carb/fat breakdown in grams.'],
        ],
        'faqs'        => [
            ['q' => 'What is the Mifflin–St Jeor equation?', 'a' => 'It estimates BMR as 10 × weight(kg) + 6.25 × height(cm) − 5 × age + 5 (men) or − 161 (women). It is considered more accurate for modern populations than the older Harris–Benedict formula.'],
            ['q' => 'What is the difference between BMR and TDEE?', 'a' => 'BMR is the calories you burn at complete rest. TDEE is BMR multiplied by an activity factor (1.2 sedentary to ~1.9 extremely active) and represents your real daily energy needs.'],
            ['q' => 'How many calories to lose or gain weight?', 'a' => 'A deficit of about 15–20% below TDEE supports fat loss; a surplus of about 10–15% supports muscle gain. This calculator applies those standard adjustments automatically.'],
            ['q' => 'How much protein should I eat?', 'a' => 'A common target is roughly 1.6–2.2 g of protein per kg of body weight for active people. The macro split here uses a protein-forward default you can use as a starting point.'],
        ],
        'related'     => ['tesamorelin', 'mots-c', 'ipamorelin'],
    ],

    // ----------------------------------------------------------------------
    'protocol' => [
        'slug'        => 'protocol',
        'name'        => 'Protocol Tool',
        'short'       => 'Protocol',
        'emoji'       => '🌐',
        'tagline'     => 'Plan a multi-peptide protocol with reconstitution and weekly timing.',
        'category'    => 'Peptide',
        'accent'      => '#0D9488',
        'seo_title'   => 'Peptide Protocol Tool — Stack Planner, Reconstitution & Timing',
        'seo_description' => 'Free peptide protocol planner. Select peptides, set vial sizes and doses, and build a weekly schedule with reconstitution units and an AM/PM timing grid. Research use only.',
        'intro'       => 'Running more than one peptide means tracking several vials, concentrations, doses and injection times at once. This protocol tool lets you assemble a research plan: pick the peptides you are studying, enter each vial size and target dose, and it returns the reconstitution units for each plus a consolidated weekly timing grid. It is a planning and record-keeping aid for educational purposes only.',
        'how_to'      => [
            ['title' => 'Add peptides to your protocol', 'body' => 'Select one or more peptides from the list. Common research stacks (e.g. BPC-157 + TB-500) are quick to assemble.'],
            ['title' => 'Set vial size and dose', 'body' => 'For each peptide, enter the vial mg, the bacteriostatic water you will add, and your target per-injection dose.'],
            ['title' => 'Choose frequency and timing', 'body' => 'Set how many times per week and whether it is taken AM, PM, or both. The tool builds a weekly grid.'],
            ['title' => 'Review your plan', 'body' => 'Each peptide shows its concentration and syringe units, and the weekly grid shows what to take when.'],
        ],
        'faqs'        => [
            ['q' => 'How do I plan a peptide stack?', 'a' => 'List each peptide, reconstitute it (vial mg ÷ water mL), convert your dose to syringe units, then map injection days and times on a weekly grid. This tool automates all of those steps in one place.'],
            ['q' => 'Can I run two peptides at the same time?', 'a' => 'Many research protocols pair complementary peptides (for example BPC-157 with TB-500 for tissue-repair studies). The tool keeps each one’s reconstitution and timing separate so nothing gets mixed up.'],
            ['q' => 'Should peptides be taken in the morning or evening?', 'a' => 'Timing depends on the compound — growth-hormone secretagogues are often taken before bed or fasted, for example. The tool lets you assign AM/PM per peptide so you can record your intended schedule.'],
            ['q' => 'Is this protocol tool medical advice?', 'a' => 'No. It is an educational planner that does the arithmetic and scheduling. It does not recommend compounds, doses or combinations and is not a substitute for professional guidance.'],
        ],
        'related'     => ['bpc-157', 'tb-500', 'ipamorelin', 'cjc-1295-dac'],
    ],

    // ----------------------------------------------------------------------
    'tdee' => [
        'slug'        => 'tdee',
        'name'        => 'TDEE Calculator',
        'short'       => 'TDEE',
        'emoji'       => '🔥',
        'tagline'     => 'Find your Total Daily Energy Expenditure and calorie targets.',
        'category'    => 'Body',
        'accent'      => '#F97316',
        'seo_title'   => 'TDEE Calculator — Total Daily Energy Expenditure & Calories',
        'seo_description' => 'Free TDEE calculator using the Mifflin–St Jeor equation. Find your Total Daily Energy Expenditure, BMR, and calorie targets for fat loss, maintenance and muscle gain.',
        'intro'       => 'Total Daily Energy Expenditure (TDEE) is the number of calories you burn in a day — your Basal Metabolic Rate (the energy used at rest) scaled by how active you are. It is the single most useful number for any nutrition goal: eat below it to lose fat, at it to maintain, above it to gain. This calculator estimates your BMR with the Mifflin–St Jeor equation, applies an activity multiplier, and shows your TDEE plus calorie targets for each goal.',
        'how_to'      => [
            ['title' => 'Enter your stats', 'body' => 'Provide age, sex, height and weight in metric or imperial units.'],
            ['title' => 'Select activity level', 'body' => 'Choose from sedentary to extremely active — this multiplier converts BMR into TDEE.'],
            ['title' => 'Read your TDEE', 'body' => 'See your BMR and TDEE, plus a breakdown of TDEE at every activity level for comparison.'],
            ['title' => 'Pick a calorie target', 'body' => 'Use the suggested fat-loss, maintenance and muscle-gain calorie numbers as your daily intake goal.'],
        ],
        'faqs'        => [
            ['q' => 'What is TDEE?', 'a' => 'TDEE (Total Daily Energy Expenditure) is the total calories you burn per day, including your resting metabolism, daily movement, exercise and the energy used to digest food. It is your real daily calorie need.'],
            ['q' => 'How is TDEE calculated?', 'a' => 'TDEE = BMR × an activity factor. BMR is estimated with the Mifflin–St Jeor equation, then multiplied by 1.2 (sedentary) up to about 1.9 (extremely active) depending on your weekly activity.'],
            ['q' => 'How accurate is a TDEE calculator?', 'a' => 'TDEE estimates are usually within 10–15% for most people. Use the number as a starting point, then adjust based on how your weight actually changes over 2–3 weeks.'],
            ['q' => 'How do I use TDEE to lose weight?', 'a' => 'Eat below your TDEE — a deficit of roughly 15–20% supports steady fat loss. To gain muscle, eat slightly above TDEE. The calculator shows both targets automatically.'],
        ],
        'related'     => ['tesamorelin', 'mots-c', 'ipamorelin', 'semaglutide'],
    ],

    // ----------------------------------------------------------------------
    'body-fat' => [
        'slug'        => 'body-fat',
        'name'        => 'Body Fat Calculator',
        'short'       => 'Body Fat',
        'emoji'       => '📐',
        'tagline'     => 'Estimate body fat percentage with the U.S. Navy method.',
        'category'    => 'Body',
        'accent'      => '#14B8A6',
        'seo_title'   => 'Body Fat Calculator — U.S. Navy Method Body Fat Percentage',
        'seo_description' => 'Free body fat percentage calculator using the U.S. Navy tape method. Enter neck, waist (and hip) measurements to estimate body fat %, fat mass, lean mass and category.',
        'intro'       => 'The U.S. Navy method estimates body fat percentage from simple tape measurements — neck and waist for men, plus hips for women — alongside your height. It is one of the most accessible ways to track body composition at home without callipers or a scan. Enter your measurements and this calculator returns your estimated body fat percentage, the category it falls into, and your fat-mass and lean-mass split.',
        'how_to'      => [
            ['title' => 'Choose sex and units', 'body' => 'Body fat formulas differ by sex; women also include a hip measurement. Switch between metric (cm) and imperial (in).'],
            ['title' => 'Measure neck and waist', 'body' => 'Measure your neck below the larynx and your waist at the navel, relaxed. Women also measure the hips at the widest point.'],
            ['title' => 'Enter height and weight', 'body' => 'Add your height (used by the formula) and weight (used to split fat mass from lean mass).'],
            ['title' => 'Read your body fat %', 'body' => 'See your estimated body fat percentage, category, and the kilograms (or pounds) of fat versus lean mass.'],
        ],
        'faqs'        => [
            ['q' => 'How does the U.S. Navy body fat method work?', 'a' => 'It uses a logarithmic formula based on the circumference of your neck and waist (plus hips for women) relative to your height. The differences between these measurements correlate with body fat.'],
            ['q' => 'How accurate is the Navy body fat calculator?', 'a' => 'The Navy method is typically accurate to within 3–4% of a DEXA scan for most people, which makes it a reliable, free way to track changes over time. Consistent measuring technique matters more than a single reading.'],
            ['q' => 'What is a healthy body fat percentage?', 'a' => 'General ranges: men 10–20% and women 18–28% are commonly considered healthy. Athletes are often lower; essential fat is roughly 3–5% for men and 10–13% for women.'],
            ['q' => 'How do I measure correctly?', 'a' => 'Use a flexible tape, keep it level and snug but not compressing the skin, measure on bare skin, and take each measurement two or three times to average out error.'],
        ],
        'related'     => ['tesamorelin', 'mots-c', 'semaglutide', 'tirzepatide'],
    ],

    // ----------------------------------------------------------------------
    'macro' => [
        'slug'        => 'macro',
        'name'        => 'Macro Calculator',
        'short'       => 'Macros',
        'emoji'       => '🥗',
        'tagline'     => 'Turn a calorie target into protein, carb and fat grams.',
        'category'    => 'Body',
        'accent'      => '#16A34A',
        'seo_title'   => 'Macro Calculator — Protein, Carbs & Fat Grams by Goal',
        'seo_description' => 'Free macro calculator. Enter your daily calories (or TDEE) and goal to get protein, carbohydrate and fat targets in grams for balanced, high-protein, low-carb or keto splits.',
        'intro'       => 'Once you know how many calories to eat, macros decide what those calories are made of — protein, carbohydrate and fat. Getting enough protein protects muscle, while your carb-to-fat balance is mostly preference and performance. This calculator takes your daily calorie target (and body weight, for a protein floor) and splits it into gram targets for the diet style you choose: balanced, high-protein, low-carb or ketogenic.',
        'how_to'      => [
            ['title' => 'Enter your calories', 'body' => 'Type your daily calorie target. Not sure? Use the TDEE calculator first, then bring the number here.'],
            ['title' => 'Add your weight', 'body' => 'Your body weight sets a sensible protein floor (grams of protein per kg or lb).'],
            ['title' => 'Choose a diet style', 'body' => 'Pick balanced, high-protein, low-carb or keto — each shifts the carb-to-fat ratio while keeping protein adequate.'],
            ['title' => 'Read your macros', 'body' => 'See your protein, carbohydrate and fat targets in grams, with the calorie split for each.'],
        ],
        'faqs'        => [
            ['q' => 'What are macros?', 'a' => 'Macronutrients — protein, carbohydrate and fat — are the three nutrients that provide calories. Protein and carbs have about 4 calories per gram, fat has about 9. Your macro split is how your total calories are divided among them.'],
            ['q' => 'How much protein should I eat?', 'a' => 'A common range is 1.6–2.2 g of protein per kg of body weight for active people aiming to build or retain muscle. This calculator sets protein from your weight first, then fills the rest with carbs and fat.'],
            ['q' => 'What is a good macro split?', 'a' => 'A balanced split is roughly 30% protein / 40% carbs / 30% fat. Low-carb and keto shift calories from carbs to fat; high-protein raises protein. The best split is the one you can stick to while hitting your protein target.'],
            ['q' => 'Do I need to count macros to lose weight?', 'a' => 'Total calories drive weight change, but hitting a protein target while in a calorie deficit helps preserve muscle and control hunger — which is why macros are worth tracking, not just calories.'],
        ],
        'related'     => ['tesamorelin', 'ipamorelin', 'mots-c', 'semaglutide'],
    ],

    // ----------------------------------------------------------------------
    'weight-loss' => [
        'slug'        => 'weight-loss',
        'name'        => 'GLP-1 Weight Loss Calculator',
        'short'       => 'Weight Loss',
        'emoji'       => '⚖️',
        'tagline'     => 'Estimate your timeline and time-to-goal on semaglutide or tirzepatide.',
        'category'    => 'Peptide',
        'accent'      => '#8B5CF6',
        'seo_title'   => 'GLP-1 Weight Loss Calculator — Semaglutide & Tirzepatide Timeline',
        'seo_description' => 'Free GLP-1 weight-loss calculator. Enter your current and goal weight to estimate how long it could take to reach it on semaglutide or tirzepatide, using average published response rates.',
        'intro'       => 'GLP-1 receptor agonists like semaglutide and tirzepatide produce gradual, steady weight loss over many months. This calculator works backwards from a goal: enter your current weight and a target weight, pick a compound, and it estimates roughly how long reaching that goal could take based on average percentage-loss curves from the clinical trials — along with your projected weight and BMI at each milestone. It is an educational estimate; individual results vary widely.',
        'how_to'      => [
            ['title' => 'Select the compound', 'body' => 'Choose semaglutide or tirzepatide — each has a different average response curve in the published trials.'],
            ['title' => 'Enter current and goal weight', 'body' => 'Provide your height, current weight and the weight you want to reach, in metric or imperial units.'],
            ['title' => 'See your estimated timeline', 'body' => 'The calculator estimates the number of weeks to reach your goal at average response rates, plus your goal BMI.'],
            ['title' => 'Review the milestones', 'body' => 'A milestone table shows projected weight and BMI at 4, 12, 24, 52 and 68 weeks so you can see the trajectory.'],
        ],
        'faqs'        => [
            ['q' => 'How much weight can you lose on semaglutide or tirzepatide?', 'a' => 'In trials, average reduction at about 68 weeks was roughly 15% of body weight for semaglutide and 20%+ for tirzepatide at higher doses. These are study averages — some people lose more, some less.'],
            ['q' => 'How long does it take to reach a weight-loss goal?', 'a' => 'Loss is gradual because the dose is titrated up over the first few months. This calculator estimates the week at which average response rates would reach your target percentage loss; very large goals may fall beyond the typical trial range.'],
            ['q' => 'Is this weight-loss estimate guaranteed?', 'a' => 'No. It is an illustrative model built on average published outcomes and does not account for your diet, activity, genetics or medical history. Use it for planning, not as a promise of results.'],
            ['q' => 'What is a realistic monthly weight loss on GLP-1s?', 'a' => 'After titration, many people lose roughly 1–2% of body weight per month on average, faster early and tapering over time. The milestone table reflects this curved, non-linear pattern.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide', 'cagrilintide'],
    ],

    // ----------------------------------------------------------------------
    'glp-1-units' => [
        'slug'        => 'glp-1-units',
        'name'        => 'GLP-1 Dose Converter',
        'short'       => 'Dose Converter',
        'emoji'       => '🧮',
        'tagline'     => 'Convert a weekly GLP-1 mg dose into insulin-syringe units.',
        'category'    => 'Peptide',
        'accent'      => '#6366F1',
        'seo_title'   => 'GLP-1 Dose Converter — Semaglutide & Tirzepatide mg to Units',
        'seo_description' => 'Free GLP-1 dose converter. Reconstitute your semaglutide or tirzepatide vial and convert any weekly mg dose into the exact insulin-syringe units to draw, with a full dose-ladder reference table.',
        'intro'       => 'GLP-1 peptides are dosed weekly in milligrams, but you draw them in units on an insulin syringe — and the conversion depends entirely on how you reconstituted the vial. This converter does both steps: enter your vial size and bacteriostatic water, pick a compound, and it shows the units to draw for any weekly dose, plus a reference table for the entire standard dose ladder so you can read off every titration step at a glance.',
        'how_to'      => [
            ['title' => 'Pick a compound', 'body' => 'Choose semaglutide or tirzepatide to load its standard weekly dose ladder, or enter a custom dose.'],
            ['title' => 'Reconstitute the vial', 'body' => 'Enter the total mg of peptide in the vial and the bacteriostatic water you are adding.'],
            ['title' => 'Enter your weekly dose', 'body' => 'Type the weekly dose in mg. The converter returns the exact units and mL to draw on a U-100 syringe.'],
            ['title' => 'Use the reference table', 'body' => 'The table converts every step of the standard ladder into units for your exact reconstitution.'],
        ],
        'faqs'        => [
            ['q' => 'How do I convert semaglutide mg to units?', 'a' => 'First find your concentration: vial mg ÷ water mL = mg/mL. Then units = (weekly mg ÷ mg/mL) × 100, because a U-100 syringe has 100 units per mL. This converter runs both steps for any dose.'],
            ['q' => 'How many units is 0.25 mg of semaglutide?', 'a' => 'It depends on your concentration. For example, a 5 mg vial in 2 mL of water is 2.5 mg/mL, so 0.25 mg = 0.1 mL = 10 units. Change the vial and water inputs and the table updates for your setup.'],
            ['q' => 'What syringe should I use for GLP-1 peptides?', 'a' => 'A standard U-100 insulin syringe, marked in 100 units per mL (1 unit = 0.01 mL). The converter gives your dose directly in those units.'],
            ['q' => 'What is the standard semaglutide and tirzepatide dose ladder?', 'a' => 'Semaglutide commonly steps 0.25 → 0.5 → 1.0 → 1.7 → 2.4 mg; tirzepatide steps 2.5 → 5 → 7.5 → 10 → 12.5 → 15 mg, each held about 4 weeks. The reference table converts every step into units.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    // ---- Batch 1: peptide dosing & research tools ----

    'peptide-cost-per-dose' => [
        'slug'        => 'peptide-cost-per-dose',
        'name'        => 'Peptide Cost Per Dose Calculator',
        'short'       => 'Cost Per Dose',
        'emoji'       => '💲',
        'tagline'     => 'Work out the true cost of one dose — and per week and month.',
        'category'    => 'Peptide',
        'accent'      => '#0EA5E9',
        'seo_title'   => 'Peptide Cost Per Dose Calculator — Price Per Injection & Per Month',
        'seo_description' => 'Free peptide cost calculator. Enter the vial price, vial size and your dose to see the real cost per dose, per week and per month, plus how many doses each vial yields.',
        'intro'       => 'Vial prices look very different once you work out what a single dose actually costs. This calculator turns a vial price into the real per-dose, per-week and per-month cost based on your dosing — so you can compare products on what matters and budget a protocol accurately. Enter the vial price, the milligrams in the vial, your dose and how often you take it.',
        'how_to'      => [
            ['title' => 'Enter the vial price', 'body' => 'The price you pay for one vial. Use the same currency throughout — the result follows whatever you enter.'],
            ['title' => 'Enter the vial size', 'body' => 'Total peptide in the vial in milligrams (mg), as printed on the label.'],
            ['title' => 'Set your dose & frequency', 'body' => 'Your dose per administration (in mg or mcg) and how many times per week you dose.'],
            ['title' => 'Read your real costs', 'body' => 'The tool shows cost per dose, per week and per month, plus doses per vial and how long a vial lasts.'],
        ],
        'faqs'        => [
            ['q' => 'How do you calculate cost per dose?', 'a' => 'Cost per dose = vial price ÷ (vial mg ÷ dose mg). In other words, divide the price by the number of doses the vial contains. This calculator does it for you and also projects weekly and monthly cost from your frequency.'],
            ['q' => 'How many doses are in a vial?', 'a' => 'Doses per vial = vial size (mg) ÷ dose (mg). A 10 mg vial dosed at 0.5 mg yields 20 doses. Enter your numbers and the tool shows it instantly.'],
            ['q' => 'Why compare cost per dose instead of vial price?', 'a' => 'A cheaper vial can cost more per dose if it contains less peptide or you dose higher. Cost per dose normalises price across vial sizes and dosing so comparisons are fair.'],
            ['q' => 'Does this include bacteriostatic water or supplies?', 'a' => 'No — it isolates the peptide cost so comparisons stay clean. Add a fixed amount for water, syringes and shipping separately if you want an all-in figure.'],
        ],
        'related'     => ['bpc-157', 'tb-500', 'semaglutide', 'tirzepatide'],
    ],

    'peptide-half-life' => [
        'slug'        => 'peptide-half-life',
        'name'        => 'Peptide Half-Life & Clearance Calculator',
        'short'       => 'Half-Life',
        'emoji'       => '⏳',
        'tagline'     => 'See how much peptide remains over time and when it clears.',
        'category'    => 'Peptide',
        'accent'      => '#8B5CF6',
        'seo_title'   => 'Peptide Half-Life Calculator — Clearance Time & Amount Remaining',
        'seo_description' => 'Free peptide half-life calculator. Enter a half-life and dose to see how much remains after each half-life and the approximate time for the peptide to clear (≈5 half-lives).',
        'intro'       => 'A compound’s half-life is the time it takes for half of it to leave the system. After about five half-lives roughly 97% has cleared, which is the common rule of thumb for when a peptide is effectively gone. Enter a half-life (and optionally a dose) and this calculator shows the amount remaining after each half-life and the approximate full-clearance time — useful for spacing doses and planning washout periods in a research context.',
        'how_to'      => [
            ['title' => 'Enter the half-life', 'body' => 'In hours. Half-lives vary widely — minutes for some peptides, days for others. Use the value from the peptide’s profile or your reference.'],
            ['title' => 'Optionally enter a dose', 'body' => 'Add a starting amount (mg or mcg) to see the actual quantity remaining at each step, not just the percentage.'],
            ['title' => 'Read the decay table', 'body' => 'See the percentage (and amount) left after 1–5 half-lives.'],
            ['title' => 'Check the clearance estimate', 'body' => 'The tool shows the approximate time to ≈97% cleared (5 half-lives) — the practical “washout” window.'],
        ],
        'faqs'        => [
            ['q' => 'How long until a peptide is out of the system?', 'a' => 'The common rule is about five half-lives, after which ~96.9% has cleared. Multiply the half-life by five for an approximate full-clearance time — this calculator does it automatically.'],
            ['q' => 'How much remains after each half-life?', 'a' => 'Each half-life removes half of what is left: after 1 it is 50%, then 25%, 12.5%, 6.25% and 3.125% after five. The decay table shows this for your half-life.'],
            ['q' => 'Why does half-life matter for dosing frequency?', 'a' => 'Half-life drives how steady blood levels are. Short half-lives often mean more frequent dosing to maintain levels; long half-lives allow less frequent dosing. Always follow the protocol for the specific compound.'],
            ['q' => 'Is clearance the same as effect duration?', 'a' => 'Not always — some peptides act through downstream signalling that outlasts the molecule itself. Clearance estimates when the compound is gone, not necessarily when every effect ends.'],
        ],
        'related'     => ['bpc-157', 'ipamorelin', 'semaglutide', 'tesamorelin'],
    ],

    'peptide-cycle-planner' => [
        'slug'        => 'peptide-cycle-planner',
        'name'        => 'Peptide Cycle Planner',
        'short'       => 'Cycle Planner',
        'emoji'       => '🗓️',
        'tagline'     => 'Map on/off cycles with exact start, end and next-cycle dates.',
        'category'    => 'Peptide',
        'accent'      => '#10B981',
        'seo_title'   => 'Peptide Cycle Planner — On/Off Cycle Dates & Schedule',
        'seo_description' => 'Free peptide cycle planner. Set your cycle length, break length and start date to map exact on and off dates across multiple cycles and your next start date.',
        'intro'       => 'Many peptide protocols run in cycles — a set number of weeks “on” followed by a break “off” — to manage tolerance and give the body a rest. This planner turns your chosen cycle length, break length and start date into concrete dates: when each on-phase ends, when the break ends, and when the next cycle begins, across as many cycles as you want to map.',
        'how_to'      => [
            ['title' => 'Set the cycle length', 'body' => 'How many weeks you run the peptide in one cycle (the “on” phase).'],
            ['title' => 'Set the break length', 'body' => 'How many weeks off between cycles (the “off” phase / washout).'],
            ['title' => 'Pick a start date', 'body' => 'The day cycle 1 begins. The planner counts forward from here.'],
            ['title' => 'Read your schedule', 'body' => 'See on/off date ranges for each cycle and the exact date your next cycle starts.'],
        ],
        'faqs'        => [
            ['q' => 'Why cycle peptides on and off?', 'a' => 'Cycling is used in research protocols to limit receptor desensitisation/tolerance and to build in recovery periods. The right pattern depends entirely on the specific compound and goal.'],
            ['q' => 'What is a common cycle length?', 'a' => 'It varies by compound — healing peptides are often run in shorter blocks with breaks, while others follow different patterns. Use the cycle and break lengths from the protocol you are following; this tool just maps the dates.'],
            ['q' => 'What happens during the “off” phase?', 'a' => 'The off phase is a break from dosing that lets levels clear (see the half-life calculator) and gives signalling pathways time to reset before the next cycle.'],
            ['q' => 'Can I plan several cycles ahead?', 'a' => 'Yes — the planner projects multiple consecutive cycles so you can see the full calendar and your next start date at a glance.'],
        ],
        'related'     => ['bpc-157', 'tb-500', 'ipamorelin', 'mots-c'],
    ],

    'peptide-blend' => [
        'slug'        => 'peptide-blend',
        'name'        => 'Peptide Blend Reconstitution Calculator',
        'short'       => 'Blend',
        'emoji'       => '⚗️',
        'tagline'     => 'Two peptides in one vial — units to draw for each.',
        'category'    => 'Peptide',
        'accent'      => '#F59E0B',
        'seo_title'   => 'Peptide Blend Calculator — Two-Peptide Vial Reconstitution & Units',
        'seo_description' => 'Free peptide blend reconstitution calculator. For two peptides combined in one vial, enter each amount, the shared water volume and your target doses to get the exact units to draw on one syringe.',
        'intro'       => 'When two peptides are reconstituted together in a single vial (a “blend”), one syringe draw delivers both — so the units you draw must satisfy each peptide’s target dose at the same time. This calculator handles the shared-water maths: enter the milligrams of each peptide, the total bacteriostatic water and your target dose for each, and it returns the concentration of each, the units that deliver your primary dose, and exactly how much of the second peptide that same draw delivers.',
        'how_to'      => [
            ['title' => 'Enter each peptide amount', 'body' => 'The milligrams of peptide A and peptide B that go into the vial.'],
            ['title' => 'Enter the shared water', 'body' => 'The total bacteriostatic water (mL) added to the vial — both peptides share it.'],
            ['title' => 'Set your primary target dose', 'body' => 'The dose you are aiming for on peptide A. The tool finds the units that deliver it.'],
            ['title' => 'Check what B delivers', 'body' => 'Because it is one draw, the result shows the matching dose of peptide B you get at those same units.'],
        ],
        'faqs'        => [
            ['q' => 'How do you dose two peptides blended in one vial?', 'a' => 'Each peptide’s concentration is its mg ÷ the shared water mL. One syringe draw of X units delivers X% of 1 mL of the mixture — so it delivers the proportional dose of both peptides at once. This calculator shows the units for your primary dose and the matching amount of the second.'],
            ['q' => 'Can any two peptides be blended?', 'a' => 'Compatibility (stability and solubility together) is compound-specific and a research consideration — check the profiles for each peptide before blending. This tool only does the dosing maths once you have decided to blend.'],
            ['q' => 'Why not dose each peptide separately?', 'a' => 'Separate vials give independent control of each dose. Blends trade that flexibility for one injection — convenient when the desired dose ratio is fixed, which is exactly what this calculator helps you check.'],
            ['q' => 'What syringe does this assume?', 'a' => 'A U-100 insulin syringe (100 units = 1 mL, so 1 unit = 0.01 mL), the standard for reconstituted peptides.'],
        ],
        'related'     => ['bpc-157', 'tb-500', 'cjc-1295', 'ipamorelin'],
    ],

    'semaglutide-titration' => [
        'slug'        => 'semaglutide-titration',
        'name'        => 'Semaglutide Titration Schedule',
        'short'       => 'Sema Titration',
        'emoji'       => '📈',
        'tagline'     => 'Build a week-by-week semaglutide dose-escalation schedule.',
        'category'    => 'Peptide',
        'accent'      => '#6366F1',
        'seo_title'   => 'Semaglutide Titration Calculator — Week-by-Week Dose Schedule',
        'seo_description' => 'Free semaglutide titration schedule. Generate a week-by-week dose-escalation plan from the standard 0.25 → 2.4 mg ladder with the exact date each step begins.',
        'intro'       => 'Semaglutide is escalated slowly — typically starting at 0.25 mg weekly and stepping up roughly every four weeks — to let tolerability build before reaching a maintenance dose. This tool turns the standard ladder into a dated, week-by-week schedule from your start date, with an adjustable hold length per step, so you can see exactly which dose to take each week and when each increase is due.',
        'how_to'      => [
            ['title' => 'Pick a start date', 'body' => 'The day you begin at the first step. The schedule counts weeks forward from here.'],
            ['title' => 'Set weeks per step', 'body' => 'How long to hold each dose before stepping up (commonly ~4 weeks).'],
            ['title' => 'Choose the max dose', 'body' => 'Where the ladder stops — your intended maintenance dose.'],
            ['title' => 'Read the dated schedule', 'body' => 'Each row shows the week, the weekly dose, and the date that step begins.'],
        ],
        'faqs'        => [
            ['q' => 'What is the standard semaglutide titration?', 'a' => 'A common ladder is 0.25 → 0.5 → 1.0 → 1.7 → 2.4 mg weekly, holding each step about four weeks. The starting 0.25 mg is generally a tolerance-building dose. This tool dates each step for you; follow the protocol appropriate to your situation.'],
            ['q' => 'Why titrate slowly?', 'a' => 'Gradual escalation reduces gastrointestinal side effects (nausea is the most common) by giving the body time to adjust before each increase.'],
            ['q' => 'How long between dose increases?', 'a' => 'Around four weeks per step is typical, but the hold can be extended if a step isn’t well tolerated — set “weeks per step” to match your plan.'],
            ['q' => 'How do I convert these mg doses to syringe units?', 'a' => 'Use the GLP-1 Dose Converter — enter your vial size and water and it converts every mg step into units for your exact reconstitution.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide', 'cagrilintide'],
    ],

    'tirzepatide-titration' => [
        'slug'        => 'tirzepatide-titration',
        'name'        => 'Tirzepatide Titration Schedule',
        'short'       => 'Tirz Titration',
        'emoji'       => '📈',
        'tagline'     => 'Build a week-by-week tirzepatide dose-escalation schedule.',
        'category'    => 'Peptide',
        'accent'      => '#0D9488',
        'seo_title'   => 'Tirzepatide Titration Calculator — Week-by-Week Dose Schedule',
        'seo_description' => 'Free tirzepatide titration schedule. Generate a week-by-week dose-escalation plan from the standard 2.5 → 15 mg ladder with the exact date each step begins.',
        'intro'       => 'Tirzepatide is escalated from a 2.5 mg weekly starting dose up through the standard ladder, holding each step around four weeks so tolerability can build before the next increase. This tool turns that ladder into a dated, week-by-week schedule from your start date, with an adjustable hold length and a selectable maximum dose, so you always know the current dose and when the next step is due.',
        'how_to'      => [
            ['title' => 'Pick a start date', 'body' => 'The day you begin at 2.5 mg. The schedule counts weeks forward from here.'],
            ['title' => 'Set weeks per step', 'body' => 'How long to hold each dose before increasing (commonly ~4 weeks).'],
            ['title' => 'Choose the max dose', 'body' => 'Stop the ladder at 5, 7.5, 10, 12.5 or 15 mg — your intended maintenance dose.'],
            ['title' => 'Read the dated schedule', 'body' => 'Each row shows the week, the weekly dose and the date that step begins.'],
        ],
        'faqs'        => [
            ['q' => 'What is the standard tirzepatide titration?', 'a' => 'A common ladder is 2.5 → 5 → 7.5 → 10 → 12.5 → 15 mg weekly, holding each step about four weeks. The 2.5 mg start is a tolerance-building dose. This tool dates each step; follow the protocol appropriate to your situation.'],
            ['q' => 'How long do you stay on each dose?', 'a' => 'Roughly four weeks per step is typical, extended if a step isn’t well tolerated. Set “weeks per step” to match your plan.'],
            ['q' => 'Do I have to go all the way to 15 mg?', 'a' => 'No — maintenance can be held at any effective, well-tolerated step. Pick your max dose and the schedule stops there.'],
            ['q' => 'How do I convert mg to syringe units?', 'a' => 'Use the GLP-1 Dose Converter: enter your vial size and bacteriostatic water and it converts each mg step into the units to draw.'],
        ],
        'related'     => ['tirzepatide', 'semaglutide', 'retatrutide', 'cagrilintide'],
    ],

    // ---- Batch 2: GLP-1 / weight-loss ----

    'goal-weight-timeline' => [
        'slug'        => 'goal-weight-timeline',
        'name'        => 'Goal Weight & Timeline Calculator',
        'short'       => 'Goal Weight',
        'emoji'       => '🎯',
        'tagline'     => 'See how long to reach your goal weight at a chosen weekly rate.',
        'category'    => 'Body',
        'accent'      => '#16A34A',
        'seo_title'   => 'Goal Weight Timeline Calculator — How Long to Reach Your Target',
        'seo_description' => 'Free goal weight timeline calculator. Enter your current weight, goal weight and weekly rate to see how many weeks it takes and the exact date you reach your target.',
        'intro'       => 'Setting a goal weight is easy; knowing when you’ll get there keeps you on track. Enter your current weight, your goal weight and a realistic weekly rate of loss, and this calculator returns how many weeks it takes, the total to lose, and the calendar date you reach your target — so a GLP-1 or lifestyle protocol has a concrete finish line rather than a vague hope.',
        'how_to'      => [
            ['title' => 'Enter current and goal weight', 'body' => 'Use the same unit (lb or kg) for both. Switch units any time — the result follows.'],
            ['title' => 'Pick a weekly rate', 'body' => 'Choose a sustainable weekly loss (often ~0.5–1% of body weight). The tool uses this to project the timeline.'],
            ['title' => 'Read your timeline', 'body' => 'See the number of weeks, total weight to lose, and the projected target date.'],
            ['title' => 'Adjust to stay realistic', 'body' => 'Try different weekly rates to see how the finish date moves — faster isn’t always sustainable.'],
        ],
        'faqs'        => [
            ['q' => 'How long does it take to reach my goal weight?', 'a' => 'Weeks to goal = (current − goal) ÷ weekly loss rate. For example, losing 30 lb at 1.5 lb/week takes about 20 weeks. This calculator does the math and adds the target date.'],
            ['q' => 'What is a safe rate of weight loss?', 'a' => 'A commonly cited sustainable range is roughly 0.5–1% of body weight per week. Faster loss is possible early on (especially water weight) but tends to slow; pick a rate you can maintain.'],
            ['q' => 'Why does the timeline matter on a GLP-1 protocol?', 'a' => 'GLP-1 weight loss is gradual and tied to titration. A timeline sets realistic expectations and helps you plan dose steps — see the semaglutide and tirzepatide titration calculators.'],
            ['q' => 'Will weight loss stay linear the whole way?', 'a' => 'Rarely — loss is usually faster at first and slows as you approach your goal. Treat the timeline as a planning estimate, not a guarantee, and re-run it as your weight changes.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    'calorie-deficit' => [
        'slug'        => 'calorie-deficit',
        'name'        => 'Calorie Deficit Calculator',
        'short'       => 'Calorie Deficit',
        'emoji'       => '🔥',
        'tagline'     => 'Find the daily deficit and calorie target for your loss goal.',
        'category'    => 'Body',
        'accent'      => '#EA580C',
        'seo_title'   => 'Calorie Deficit Calculator — Daily Deficit & Target Intake',
        'seo_description' => 'Free calorie deficit calculator. Enter your maintenance calories and weekly weight-loss goal to get the daily calorie deficit and the target intake to hit it.',
        'intro'       => 'Weight loss comes down to an energy deficit — eating fewer calories than you burn. This calculator turns a weekly loss goal into the daily deficit you need and the calorie target to eat each day. Enter your maintenance calories (your TDEE) and how much you want to lose per week, and it does the rest. Roughly 3,500 kcal ≈ 1 lb of fat (7,700 kcal ≈ 1 kg).',
        'how_to'      => [
            ['title' => 'Enter maintenance calories', 'body' => 'Your TDEE — calories to maintain current weight. Use the TDEE calculator if you don’t know it.'],
            ['title' => 'Set your weekly loss goal', 'body' => 'How much you want to lose per week (lb or kg). The tool converts it to an energy deficit.'],
            ['title' => 'Read the daily deficit', 'body' => 'See the calories per day you need to cut, and your resulting daily target intake.'],
            ['title' => 'Keep it sustainable', 'body' => 'If the target drops uncomfortably low, choose a gentler weekly goal — the numbers update instantly.'],
        ],
        'faqs'        => [
            ['q' => 'How big a calorie deficit do I need to lose 1 lb a week?', 'a' => 'About 500 kcal/day. One pound of fat is ~3,500 kcal, so 3,500 ÷ 7 days ≈ 500 kcal/day. For 1 kg/week it is ~1,100 kcal/day (7,700 ÷ 7). This calculator computes it for any goal.'],
            ['q' => 'What is maintenance calories (TDEE)?', 'a' => 'Total Daily Energy Expenditure — the calories you burn in a day at your current activity level. Eating at TDEE maintains weight; below it creates the deficit that drives loss.'],
            ['q' => 'How does a GLP-1 create a deficit?', 'a' => 'GLP-1 peptides reduce appetite, which makes it easier to eat below maintenance. This calculator shows the target intake; the appetite effect helps you actually hit it.'],
            ['q' => 'Can the deficit be too aggressive?', 'a' => 'Yes — very large deficits can cost muscle and are hard to sustain. A moderate deficit with adequate protein (see the protein calculator) preserves more lean mass.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    'bmr' => [
        'slug'        => 'bmr',
        'name'        => 'BMR Calculator',
        'short'       => 'BMR',
        'emoji'       => '⚡',
        'tagline'     => 'Basal metabolic rate (Mifflin–St Jeor) plus your TDEE by activity.',
        'category'    => 'Body',
        'accent'      => '#0891B2',
        'seo_title'   => 'BMR Calculator — Basal Metabolic Rate (Mifflin–St Jeor) & TDEE',
        'seo_description' => 'Free BMR calculator using the Mifflin–St Jeor equation. Enter age, sex, height and weight to get your basal metabolic rate and your TDEE across activity levels.',
        'intro'       => 'Your basal metabolic rate (BMR) is the energy your body burns at complete rest just to keep you alive — breathing, circulation, cell repair. It’s the foundation of any calorie plan. This calculator uses the Mifflin–St Jeor equation (the modern standard) and also shows your TDEE at each activity level, so you can pick the maintenance number that matches your lifestyle.',
        'how_to'      => [
            ['title' => 'Choose units and sex', 'body' => 'Metric (cm/kg) or imperial (ft-in/lb). Sex changes the equation’s constant.'],
            ['title' => 'Enter age, height, weight', 'body' => 'The Mifflin–St Jeor equation uses all three plus sex.'],
            ['title' => 'Read your BMR', 'body' => 'The result is calories burned per day at complete rest.'],
            ['title' => 'Pick your activity for TDEE', 'body' => 'The table multiplies BMR by standard activity factors so you can read your maintenance calories.'],
        ],
        'faqs'        => [
            ['q' => 'What is the Mifflin–St Jeor BMR formula?', 'a' => 'For men: BMR = 10×kg + 6.25×cm − 5×age + 5. For women: 10×kg + 6.25×cm − 5×age − 161. This calculator applies the right one based on the sex and units you choose.'],
            ['q' => 'What is the difference between BMR and TDEE?', 'a' => 'BMR is calories at complete rest. TDEE = BMR × an activity factor (1.2 sedentary up to ~1.9 very active) and represents your real daily burn. Use TDEE as your maintenance number.'],
            ['q' => 'Why does BMR matter for weight loss?', 'a' => 'BMR is the floor your calorie target should respect — dropping intake far below BMR for long periods is hard to sustain. Knowing BMR keeps a deficit safe and realistic.'],
            ['q' => 'Is Mifflin–St Jeor accurate?', 'a' => 'It is one of the most accurate prediction equations for the general population, though individual metabolism varies. Treat it as a strong estimate and adjust based on real-world results.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'tesamorelin'],
    ],

    'weekly-weight-loss-projection' => [
        'slug'        => 'weekly-weight-loss-projection',
        'name'        => 'Weekly Weight-Loss Projection',
        'short'       => 'Loss Projection',
        'emoji'       => '📉',
        'tagline'     => 'Project your weight week-by-week at a chosen rate.',
        'category'    => 'Body',
        'accent'      => '#9333EA',
        'seo_title'   => 'Weekly Weight-Loss Projection Calculator — Week-by-Week Forecast',
        'seo_description' => 'Free weekly weight-loss projection. Enter your starting weight and weekly rate (% or fixed amount) to forecast your weight for each week ahead with dates.',
        'intro'       => 'Seeing a week-by-week forecast keeps a weight-loss protocol motivating and realistic. Enter your starting weight, choose a weekly rate — either a percentage of body weight or a fixed amount — and the number of weeks, and this tool projects your weight for every week ahead, with dates. The percentage mode mirrors how real loss tapers as you get lighter.',
        'how_to'      => [
            ['title' => 'Enter your starting weight', 'body' => 'In lb or kg. Everything is projected from here.'],
            ['title' => 'Choose a rate mode', 'body' => 'Percent of body weight per week (tapers naturally) or a fixed amount per week.'],
            ['title' => 'Set the number of weeks', 'body' => 'How far ahead to project — the table fills in each week with a date.'],
            ['title' => 'Read the forecast', 'body' => 'See projected weight per week and the total change over the period.'],
        ],
        'faqs'        => [
            ['q' => 'How is the weekly projection calculated?', 'a' => 'In percent mode, each week’s loss = current weight × rate%, so loss shrinks as you get lighter (compounding down). In fixed mode, the same amount is subtracted each week. The table shows the running weight either way.'],
            ['q' => 'Should I use percent or fixed weekly loss?', 'a' => 'Percent is more realistic for longer projections because real-world loss slows as body weight drops. Fixed is fine for short horizons or simple planning.'],
            ['q' => 'What weekly rate is realistic on a GLP-1?', 'a' => 'Gradual — often around 0.5–1% of body weight per week once titrated, varying by person. Use a conservative rate for planning and update as your real numbers come in.'],
            ['q' => 'Why does my loss slow down over time?', 'a' => 'A lighter body burns fewer calories, so the same habits create a smaller deficit. Percent mode models this; many people also adjust intake or dose as they progress.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    'retatrutide-dosage' => [
        'slug'        => 'retatrutide-dosage',
        'name'        => 'Retatrutide Dosage Calculator',
        'short'       => 'Retatrutide',
        'emoji'       => '🧪',
        'tagline'     => 'Reconstitute retatrutide and convert weekly mg to units.',
        'category'    => 'Peptide',
        'accent'      => '#DB2777',
        'seo_title'   => 'Retatrutide Dosage Calculator — Reconstitution & mg to Units',
        'seo_description' => 'Free retatrutide dosage calculator. Enter your vial size and bacteriostatic water, then convert any weekly retatrutide dose into the exact insulin-syringe units to draw.',
        'intro'       => 'Retatrutide is dosed weekly in milligrams but drawn in units on an insulin syringe, and the conversion depends on how the vial was reconstituted. Enter the vial size and the bacteriostatic water you are adding, then enter a weekly dose to get the exact units and millilitres to draw on a U-100 syringe — plus a reference table across a typical escalating dose range so you can read every step for your reconstitution.',
        'how_to'      => [
            ['title' => 'Reconstitute the vial', 'body' => 'Enter the total mg of retatrutide in the vial and the bacteriostatic water (mL) you are adding.'],
            ['title' => 'Enter your weekly dose', 'body' => 'Type the weekly dose in mg. The tool converts it to units and mL on a U-100 syringe.'],
            ['title' => 'Read the draw', 'body' => 'See the exact units to draw and the concentration, plus how many weekly doses the vial holds.'],
            ['title' => 'Use the reference table', 'body' => 'The table converts a typical escalating dose range into units for your exact reconstitution.'],
        ],
        'faqs'        => [
            ['q' => 'How do I convert retatrutide mg to units?', 'a' => 'Concentration = vial mg ÷ water mL. Units = (weekly mg ÷ concentration) × 100, since a U-100 syringe holds 100 units per mL. This calculator runs both steps for any dose.'],
            ['q' => 'Is retatrutide titrated like other GLP-1s?', 'a' => 'Yes — like semaglutide and tirzepatide it is escalated gradually from a low starting dose to manage tolerability. Follow the specific protocol you are using; this tool handles the reconstitution and unit conversion at each step.'],
            ['q' => 'What vial size and water should I use?', 'a' => 'There is no single right answer — more water dilutes the peptide so each unit holds less, making small doses easier to read. Choose a combination that places your dose at an easy-to-measure number of units.'],
            ['q' => 'What syringe is assumed?', 'a' => 'A standard U-100 insulin syringe (100 units = 1 mL, 1 unit = 0.01 mL).'],
        ],
        'related'     => ['retatrutide', 'tirzepatide', 'semaglutide', 'cagrilintide'],
    ],

    // ---- Batch 3: general fitness & body ----

    'protein-intake' => [
        'slug'        => 'protein-intake',
        'name'        => 'Protein Intake Calculator',
        'short'       => 'Protein',
        'emoji'       => '🥩',
        'tagline'     => 'Daily protein target for your weight and goal.',
        'category'    => 'Body',
        'accent'      => '#DC2626',
        'seo_title'   => 'Protein Intake Calculator — Daily Grams for Your Goal',
        'seo_description' => 'Free protein intake calculator. Enter your weight and goal (maintain, lose fat, build muscle) to get your recommended daily protein range in grams.',
        'intro'       => 'Protein is the nutrient that preserves muscle in a calorie deficit and builds it in a surplus — which is why it matters on any body-composition or GLP-1 protocol where overall intake drops. This calculator turns your body weight and goal into a daily protein target range in grams, using the gram-per-kilogram ranges commonly cited in sports-nutrition research.',
        'how_to'      => [
            ['title' => 'Enter your weight', 'body' => 'In lb or kg — switch units any time.'],
            ['title' => 'Pick your goal', 'body' => 'Maintain, lose fat (higher protein protects muscle), or build muscle.'],
            ['title' => 'Read your range', 'body' => 'The result shows a sensible low–high daily protein target in grams for your goal.'],
            ['title' => 'Spread it across meals', 'body' => 'Aim for roughly even protein across the day; the total is what matters most.'],
        ],
        'faqs'        => [
            ['q' => 'How much protein do I need per day?', 'a' => 'Common research-based ranges are ~0.8 g/kg for sedentary maintenance, ~1.2–1.6 g/kg for active people, and ~1.6–2.2 g/kg when losing fat or building muscle. This calculator applies the range for your goal to your weight.'],
            ['q' => 'Why eat more protein when losing weight?', 'a' => 'In a calorie deficit, higher protein helps preserve lean muscle (so more of the loss is fat) and increases satiety, which makes the deficit easier to maintain.'],
            ['q' => 'Does protein need matter on a GLP-1?', 'a' => 'Yes — appetite suppression can cut total intake sharply, so deliberately hitting a protein target protects muscle while you lose fat. Pair it with the calorie-deficit calculator.'],
            ['q' => 'Can I eat too much protein?', 'a' => 'For healthy individuals, intakes within these ranges are well tolerated. Very high intakes offer little extra benefit for most people; prioritise hitting the target, not exceeding it.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'ipamorelin'],
    ],

    'water-intake' => [
        'slug'        => 'water-intake',
        'name'        => 'Water Intake Calculator',
        'short'       => 'Water',
        'emoji'       => '💧',
        'tagline'     => 'Daily hydration target based on weight and activity.',
        'category'    => 'Body',
        'accent'      => '#0EA5E9',
        'seo_title'   => 'Water Intake Calculator — Daily Hydration Needs',
        'seo_description' => 'Free water intake calculator. Enter your weight and activity level to get your recommended daily water intake in litres and ounces.',
        'intro'       => 'Hydration supports nearly every process in the body, and needs scale with body size and activity. This calculator estimates a sensible daily water target from your weight and how active you are, in both litres and ounces. It uses the common ~30–35 mL per kilogram baseline plus an allowance for exercise — a practical starting point, not a rigid rule.',
        'how_to'      => [
            ['title' => 'Enter your weight', 'body' => 'In lb or kg. The baseline scales with body mass.'],
            ['title' => 'Set your activity', 'body' => 'More activity adds an exercise allowance to the baseline.'],
            ['title' => 'Read your target', 'body' => 'See your estimated daily water in litres and fluid ounces.'],
            ['title' => 'Adjust for heat & sweat', 'body' => 'Hot climates and heavy sweating increase needs — treat the number as a floor and drink to thirst beyond it.'],
        ],
        'faqs'        => [
            ['q' => 'How much water should I drink a day?', 'a' => 'A common estimate is about 30–35 mL per kg of body weight, plus extra for exercise. For a 70 kg person that is roughly 2.1–2.5 L baseline. This calculator personalises it to your weight and activity.'],
            ['q' => 'Does food count toward hydration?', 'a' => 'Yes — water-rich foods and other drinks contribute to total fluid intake. The target here is a practical guide for fluids you drink, not a strict quota.'],
            ['q' => 'Do peptides or GLP-1s change hydration needs?', 'a' => 'GLP-1 users sometimes drink less because appetite (and thirst cues) drop, and some experience GI effects, so being deliberate about water helps. Always adjust for your own situation.'],
            ['q' => 'Can you drink too much water?', 'a' => 'Excessive intake in a short time can dilute blood sodium (hyponatremia), which is rare but serious. Spread intake across the day rather than forcing large volumes at once.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide'],
    ],

    'ideal-body-weight' => [
        'slug'        => 'ideal-body-weight',
        'name'        => 'Ideal Body Weight Calculator',
        'short'       => 'Ideal Weight',
        'emoji'       => '⚖️',
        'tagline'     => 'Reference healthy weight for your height (Devine + BMI range).',
        'category'    => 'Body',
        'accent'      => '#7C3AED',
        'seo_title'   => 'Ideal Body Weight Calculator — Devine Formula & Healthy Range',
        'seo_description' => 'Free ideal body weight calculator. Enter your height and sex to get the Devine-formula ideal weight plus the healthy-weight range for your height.',
        'intro'       => '“Ideal body weight” is a reference figure used in clinical and fitness settings as a target or a starting point — not a strict rule, since healthy bodies vary. This calculator gives the widely used Devine-formula value for your height and sex, alongside the healthy-weight range that corresponds to a normal BMI for that height, so you have both a single number and a realistic band.',
        'how_to'      => [
            ['title' => 'Choose units and sex', 'body' => 'Metric or imperial; the Devine formula uses a sex-specific base.'],
            ['title' => 'Enter your height', 'body' => 'The formula and the BMI range are both height-driven.'],
            ['title' => 'Read your ideal weight', 'body' => 'See the Devine reference figure in your chosen unit.'],
            ['title' => 'Use the healthy range', 'body' => 'The BMI-based range (18.5–24.9) gives a realistic band around the single number.'],
        ],
        'faqs'        => [
            ['q' => 'How is ideal body weight calculated?', 'a' => 'The Devine formula: men = 50 kg + 2.3 kg for each inch over 5 ft; women = 45.5 kg + 2.3 kg per inch over 5 ft. This calculator applies it and converts to your unit.'],
            ['q' => 'Is ideal body weight the same as a healthy weight?', 'a' => 'Not exactly — it is one reference point. A healthy weight is better thought of as a range (a normal BMI band for your height), which this tool also shows. Body composition matters too.'],
            ['q' => 'Why doesn’t the formula use my current weight?', 'a' => 'Ideal body weight depends on height and sex, not current weight — that is the point. Compare it to your current weight to gauge how far a goal is.'],
            ['q' => 'Should very muscular people use this?', 'a' => 'Like BMI, height-based formulas don’t account for muscle, so athletes can sit above “ideal” while being lean and healthy. Use it as a rough reference, not a verdict.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    'lean-body-mass' => [
        'slug'        => 'lean-body-mass',
        'name'        => 'Lean Body Mass Calculator',
        'short'       => 'Lean Mass',
        'emoji'       => '💪',
        'tagline'     => 'Estimate lean mass and fat mass (Boer formula).',
        'category'    => 'Body',
        'accent'      => '#059669',
        'seo_title'   => 'Lean Body Mass Calculator — LBM & Fat Mass (Boer Formula)',
        'seo_description' => 'Free lean body mass calculator using the Boer formula. Enter sex, height and weight to estimate your lean mass and fat mass.',
        'intro'       => 'Lean body mass (LBM) is everything in your body that isn’t fat — muscle, bone, organs and water. Tracking it matters because the goal of most protocols is to lose fat while keeping lean mass. This calculator estimates LBM and fat mass from your height, weight and sex using the Boer formula, a well-regarded predictive equation.',
        'how_to'      => [
            ['title' => 'Choose units and sex', 'body' => 'The Boer formula uses sex-specific coefficients.'],
            ['title' => 'Enter height and weight', 'body' => 'Both feed the estimate; switch units freely.'],
            ['title' => 'Read LBM and fat mass', 'body' => 'See your estimated lean mass and the remaining fat mass.'],
            ['title' => 'Track it over time', 'body' => 'On a cut, aim to hold LBM steady while total weight drops — that means you’re losing fat, not muscle.'],
        ],
        'faqs'        => [
            ['q' => 'What is the Boer formula for lean body mass?', 'a' => 'Men: LBM = 0.407×kg + 0.267×cm − 19.2. Women: LBM = 0.252×kg + 0.473×cm − 48.3. This calculator applies the right one and reports fat mass as weight minus LBM.'],
            ['q' => 'Why track lean body mass on a diet?', 'a' => 'Weight alone can’t tell you whether you’re losing fat or muscle. Holding LBM while total weight falls confirms the loss is mostly fat — the desirable outcome.'],
            ['q' => 'How do I preserve lean mass while losing weight?', 'a' => 'Adequate protein (see the protein calculator), resistance training, and a moderate rather than extreme deficit all help retain LBM during fat loss.'],
            ['q' => 'Is this the same as a body-fat measurement?', 'a' => 'It’s an estimate from height/weight/sex, not a direct measurement. For more precision, combine it with a body-fat method; use this for convenient tracking of the trend.'],
        ],
        'related'     => ['ipamorelin', 'tesamorelin', 'semaglutide'],
    ],

    'waist-to-height-ratio' => [
        'slug'        => 'waist-to-height-ratio',
        'name'        => 'Waist-to-Height Ratio Calculator',
        'short'       => 'Waist/Height',
        'emoji'       => '📏',
        'tagline'     => 'A simple central-fat marker — keep it under 0.5.',
        'category'    => 'Body',
        'accent'      => '#D97706',
        'seo_title'   => 'Waist-to-Height Ratio Calculator — WHtR & Health Category',
        'seo_description' => 'Free waist-to-height ratio (WHtR) calculator. Enter your waist and height to get your ratio and where it falls on the standard health bands.',
        'intro'       => 'Waist-to-height ratio (WHtR) is a quick, evidence-backed marker of central (abdominal) fat — often a better risk indicator than BMI because it reflects where fat sits. The widely used guideline is simple: keep your waist to less than half your height. Enter both measurements (same unit) and this calculator returns your ratio and the standard category it falls into.',
        'how_to'      => [
            ['title' => 'Measure your waist', 'body' => 'Around the navel, relaxed, not sucking in. Use the same unit as your height.'],
            ['title' => 'Enter your height', 'body' => 'Same unit as the waist (in or cm) — the ratio is unit-independent.'],
            ['title' => 'Read your ratio', 'body' => 'WHtR = waist ÷ height. The result shows the number and its band.'],
            ['title' => 'Aim under 0.5', 'body' => 'The common target is below 0.5; higher ratios suggest more central fat.'],
        ],
        'faqs'        => [
            ['q' => 'What is a healthy waist-to-height ratio?', 'a' => 'The widely cited guideline is to keep your waist under half your height — a ratio below 0.5. Roughly: under 0.4 may be low, 0.4–0.49 healthy, 0.5–0.59 increased, 0.6+ high.'],
            ['q' => 'Why use WHtR instead of BMI?', 'a' => 'WHtR captures central fat, which carries more metabolic risk, and works across heights with a single threshold. Many researchers consider it a stronger simple risk screen than BMI.'],
            ['q' => 'Does the unit matter?', 'a' => 'No — because it’s a ratio of two lengths, inches or centimetres give the same result, as long as you use the same unit for both.'],
            ['q' => 'How does fat loss change my ratio?', 'a' => 'Central fat is often among the first to reduce on a sustained deficit, so WHtR is a useful, cheap way to track progress between weigh-ins.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide', 'retatrutide'],
    ],

    'one-rep-max' => [
        'slug'        => 'one-rep-max',
        'name'        => 'One-Rep Max (1RM) Calculator',
        'short'       => '1RM',
        'emoji'       => '🏋️',
        'tagline'     => 'Estimate your 1RM and percentage training loads.',
        'category'    => 'Body',
        'accent'      => '#4F46E5',
        'seo_title'   => 'One-Rep Max Calculator — Estimate 1RM & Training Percentages',
        'seo_description' => 'Free one-rep max (1RM) calculator. Enter a weight and reps to estimate your one-rep max plus a full percentage table for programming your training loads.',
        'intro'       => 'Your one-rep max (1RM) is the most weight you can lift for a single repetition — the reference point most strength programs are built around. Testing a true 1RM is risky, so this calculator estimates it from a set you’ve already done (weight × reps) using the Epley formula, then gives a percentage table so you can program working sets at 50–95% without maxing out.',
        'how_to'      => [
            ['title' => 'Enter the weight lifted', 'body' => 'The load you used for the set, in lb or kg.'],
            ['title' => 'Enter the reps', 'body' => 'How many clean reps you completed (best for ~3–10 reps).'],
            ['title' => 'Read your estimated 1RM', 'body' => 'The Epley formula projects your single-rep max.'],
            ['title' => 'Use the percentage table', 'body' => 'Program working sets at common percentages of your 1RM.'],
        ],
        'faqs'        => [
            ['q' => 'How is one-rep max estimated?', 'a' => 'This tool uses the Epley formula: 1RM = weight × (1 + reps ÷ 30). For example, 100 kg for 5 reps ≈ 117 kg. Estimates are most accurate in the ~3–10 rep range.'],
            ['q' => 'Why not just test my real 1RM?', 'a' => 'A true max attempt carries higher injury risk and requires a spotter and full readiness. Estimating from a submaximal set is safer and accurate enough for programming.'],
            ['q' => 'What are the percentages for?', 'a' => 'Strength programs prescribe loads as a percentage of 1RM (e.g. 5×5 at 80%). The table converts your estimated max into those working weights.'],
            ['q' => 'How accurate is the estimate?', 'a' => 'Formula estimates are close for moderate rep ranges but drift at very high reps. Re-test from a fresh set periodically and adjust as you get stronger.'],
        ],
        'related'     => ['ipamorelin', 'tesamorelin'],
    ],

    'heart-rate-zones' => [
        'slug'        => 'heart-rate-zones',
        'name'        => 'Heart Rate Zone Calculator',
        'short'       => 'HR Zones',
        'emoji'       => '❤️',
        'tagline'     => 'Find your five training heart-rate zones from your age.',
        'category'    => 'Body',
        'accent'      => '#E11D48',
        'seo_title'   => 'Heart Rate Zone Calculator — Max HR & 5 Training Zones',
        'seo_description' => 'Free heart rate zone calculator. Enter your age (and optional resting heart rate) to get your max heart rate and the five training zones in beats per minute.',
        'intro'       => 'Training by heart-rate zones lets you target the right intensity — fat-burning and endurance at the low end, performance at the top. This calculator estimates your maximum heart rate from your age and splits it into the five standard zones in beats per minute. Add your resting heart rate to use the more individualised Karvonen (heart-rate-reserve) method.',
        'how_to'      => [
            ['title' => 'Enter your age', 'body' => 'Used to estimate maximum heart rate (≈220 − age).'],
            ['title' => 'Optional: resting HR', 'body' => 'Add it to switch to the Karvonen method, which personalises the zones.'],
            ['title' => 'Read your five zones', 'body' => 'Each zone shows its bpm range and what it trains.'],
            ['title' => 'Train to the zone', 'body' => 'Use a monitor to keep your effort in the target band for your session’s goal.'],
        ],
        'faqs'        => [
            ['q' => 'How do you calculate maximum heart rate?', 'a' => 'The classic estimate is 220 − age. This calculator uses it for the simple method; with a resting HR it switches to the Karvonen formula using heart-rate reserve (max − rest).'],
            ['q' => 'What are the five heart-rate zones?', 'a' => 'Roughly: Zone 1 50–60% (very light/recovery), Zone 2 60–70% (fat-burn/endurance), Zone 3 70–80% (aerobic), Zone 4 80–90% (threshold), Zone 5 90–100% (max effort). The tool gives bpm ranges for each.'],
            ['q' => 'What is the Karvonen method?', 'a' => 'It bases zones on heart-rate reserve: target = ((max − rest) × intensity%) + rest. Using your resting HR makes the zones more personal than a flat percentage of max.'],
            ['q' => 'Which zone burns the most fat?', 'a' => 'Lower zones (2–3) use a higher proportion of fat for fuel, but total calories burned also matter. A mix of easy zone-2 volume and occasional higher-intensity work suits most goals.'],
        ],
        'related'     => ['semaglutide', 'tirzepatide'],
    ],

];
